name: dev

services:
  mock-backend:
    image: linid-mock-backend
    container_name: linid-mock-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  default:
    name: dev-network
